# --- File: docker/docker-compose.yml (Definitive Final Version) ---
services:
  hres_postgres:
    image: postgres:13
    container_name: hres_postgres
    env_file: .env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - hres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # This service now correctly initializes the Airflow DB and exits
  airflow-init:
    container_name: airflow-init
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    env_file: .env
    entrypoint: /bin/bash
    command:
      - -c
      - |
        # --- CRITICAL FIX: Changed 'upgrade' to 'init' ---
        airflow db init
        airflow users create \
          --username ${AIRFLOW_WWW_USER_USERNAME} \
          --password ${AIRFLOW_WWW_USER_PASSWORD} \
          --firstname Shameem \
          --lastname Hossain \
          --role Admin \
          --email shameem.hossain@email.com || true
    networks:
      - hres_network
    depends_on:
      hres_postgres:
        condition: service_healthy

  hres_airflow_webserver:
    container_name: hres_airflow_webserver
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    command: airflow webserver
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - airflow_logs:/opt/airflow/logs
    networks:
      - hres_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  hres_airflow_scheduler:
    container_name: hres_airflow_scheduler
    build:
      context: ..
      dockerfile: docker/Dockerfile.airflow
    command: airflow scheduler
    env_file: .env
    volumes:
      - airflow_logs:/opt/airflow/logs
    networks:
      - hres_network
    depends_on:
      hres_airflow_webserver:
        condition: service_healthy

  hres_mlflow:
    container_name: hres_mlflow
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
    env_file: .env
    environment:
      - DB_HOST=hres_postgres
      - DB_PORT=5432
      - BACKEND_STORE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hres_postgres:5432/${POSTGRES_DB}
      - ARTIFACT_ROOT=file:/mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    ports:
      - "5000:5000"
    networks:
      - hres_network
    depends_on:
      hres_postgres:
        condition: service_healthy

  hres_api:
    container_name: hres_api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file: .env
    ports:
      - "8081:8080"
    networks:
      - hres_network
    depends_on:
      hres_mlflow:
        condition: service_started
      hres_airflow_scheduler:
        condition: service_started

  hres_jupyter:
    container_name: hres_jupyter
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - "8888:8888"
    volumes:
      - ../src:/home/jovyan/src
      - ../notebooks:/home/jovyan/notebooks
    networks:
      - hres_network

  hres_ui:
    container_name: hres_ui
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8501:8501"
    networks:
      - hres_network
    environment:
      - API_BASE_URL=http://hres_api:8080

networks:
  hres_network:
    driver: bridge

volumes:
  postgres_db_data:
  mlflow_artifacts:
  airflow_logs: