# --- File: docker/docker-compose.yml (Definitive, Simplified, Final Version) ---
# This version uses the official Apache Airflow image for guaranteed stability.
services:
  hres_postgres:
    image: postgres:13
    container_name: hres_postgres
    env_file: .env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - hres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Uses the official Airflow image. This is the key to stability.
  hres_airflow_webserver:
    image: apache/airflow:2.8.1
    container_name: hres_airflow_webserver
    env_file: .env
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ../src:/opt/airflow/src # Mount your custom modules
      - ../airflow/dags:/opt/airflow/dags # Mount your DAGs
      - airflow_logs:/opt/airflow/logs
      - ../requirements.txt:/opt/airflow/requirements.txt # Mount requirements for installation
    networks:
      - hres_network
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key_for_webserver_here
      - MLFLOW_TRACKING_URI=http://hres_mlflow:5000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      hres_postgres:
        condition: service_healthy

  hres_airflow_scheduler:
    image: apache/airflow:2.8.1
    container_name: hres_airflow_scheduler
    env_file: .env
    command: scheduler
    volumes:
      - ../src:/opt/airflow/src
      - ../airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      - ../requirements.txt:/opt/airflow/requirements.txt
    networks:
      - hres_network
    environment:
      - MLFLOW_TRACKING_URI=http://hres_mlflow:5000
    depends_on:
      hres_airflow_webserver:
        condition: service_healthy

  hres_mlflow:
    container_name: hres_mlflow
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
    env_file: .env
    environment:
      - DB_HOST=hres_postgres
      - DB_PORT=5432
      - BACKEND_STORE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hres_postgres:5432/${POSTGRES_DB}
      - ARTIFACT_ROOT=file:/mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    ports:
      - "5000:5000"
    networks:
      - hres_network
    depends_on:
      hres_postgres:
        condition: service_healthy

  hres_api:
    container_name: hres_api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file: .env
    ports:
      - "8081:8080"
    networks:
      - hres_network
    depends_on:
      hres_mlflow:
        condition: service_started
      hres_airflow_scheduler:
        condition: service_started

  hres_jupyter:
    container_name: hres_jupyter
    build:
      context: ..
      dockerfile: docker/Dockerfile.jupyter
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - "8888:8888"
    volumes:
      - ../src:/home/jovyan/src
      - ../notebooks:/home/jovyan/notebooks
    networks:
      - hres_network

  hres_ui:
    container_name: hres_ui
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8501:8501"
    networks:
      - hres_network
    environment:
      - API_BASE_URL=http://hres_api:8080

networks:
  hres_network:
    driver: bridge

volumes:
  postgres_db_data:
  mlflow_artifacts:
  airflow_logs: