FROM python:3.9-slim

RUN groupadd -r apiuser && useradd --no-log-init -r -g apiuser apiuser

WORKDIR /app

COPY ./api/ /app/api/
COPY ./src/ /app/src/
COPY HRES_Dataset.csv /app/HRES_Dataset.csv
COPY ./api/start.sh /app/start.sh

RUN chown -R apiuser:apiuser /app
USER apiuser

EXPOSE 8080

RUN chmod +x /app/start.sh  # Now run chmod as apiuser

CMD ["/app/start.sh"]
