FROM python:3.9-slim
RUN groupadd -r streamlit && useradd -r -g streamlit streamlit
WORKDIR /app
COPY ../requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./ui.py .
COPY ./logo.png .
RUN chown -R streamlit:streamlit /app
USER streamlit
EXPOSE 8501
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health
ENTRYPOINT ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]