version: "3.9"

services:
  hres_postgres:
    image: postgres:13
    container_name: hres_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - hres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  hres_api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    environment:
      API_BASE_URL: http://hres_api:8080  # Add API_BASE_URL here too
    ports:
      - "8081:8080"
    networks:
      - hres_network
    depends_on:
      hres_postgres:
        condition: service_healthy

  hres_ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    ports:
      - "8501:8501"
    environment:
      API_BASE_URL: http://hres_api:8080
    networks:
      - hres_network
    depends_on:
      - hres_api  # Ensure API is running before UI starts

  jupyter_lab:
    image: jupyter/scipy-notebook:latest
    ports:
      - "8889:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./src:/home/jovyan/src
    networks:
      - hres_network

networks:
  hres_network:
    driver: bridge

volumes:
  postgres_db_data: