FROM jupyter/scipy-notebook:latest
USER root
COPY ../requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt
COPY ./notebooks/ /home/jovyan/notebooks/
COPY ./src/ /home/jovyan/src/
RUN chown -R jovyan:jovyan /home/jovyan/notebooks && \
    chown -R jovyan:jovyan /home/jovyan/src
USER ${NB_USER}
EXPOSE 8888